web:
    build: .
    volumes:
        - 'bgg-api:/src/bgg-api'
    ports:
        - '80:3000'
    links:
        - herokuRedis
    command: 'bash -c ''cd /app/user/api; npm start'''
herokuRedis:
  image: redis
  ports:
        - '16379:6379'
