web:
    build: .
    volumes:
        - 'bgg-api:/src/bgg-api'
    ports:
        - '8080:8080'
        - '3030:3000'
        - '35729:35729'
    links:
        - herokuRedis
    command: 'bash -c ''cd /app/user/api; npm install; npm start'''
herokuRedis:
  image: redis
  ports:
        - '16379:6379'
